worker_processes auto;
error_log /dev/stderr info;

events {
    worker_connections 1024;
}

# stream {
#     # PQC SMTP Proxy
#     server {
#         listen 1025 ssl;
#         proxy_pass mail:25;
#         
#         ssl_certificate     /etc/nginx/ssl/pqc_cert.pem;
#         ssl_certificate_key /etc/nginx/ssl/pqc_key.pem;
#         ssl_ecdh_curve      kyber768:p521_kyber1024; # Hybrid support
#     }
#
#     # PQC IMAP Proxy
#     server {
#         listen 1143 ssl;
#         proxy_pass mail:143;
#         
#         ssl_certificate     /etc/nginx/ssl/pqc_cert.pem;
#         ssl_certificate_key /etc/nginx/ssl/pqc_key.pem;
#         ssl_ecdh_curve      kyber768;
#     }
# }

http {
    server {
        listen 443 ssl;
        server_name _;

        location / {
            proxy_pass http://roundcube:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Proxy for Key Service API to solve CORS and Mixed Content issues
        location /api/ {
            proxy_pass http://key_service:8081/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        ssl_certificate     /etc/nginx/ssl/pqc_cert.pem;
        ssl_certificate_key /etc/nginx/ssl/pqc_key.pem;
        ssl_ciphers         "DEFAULT:@SECLEVEL=0";
    }
}
